# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: akhercha <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/07/22 10:18:17 by akhercha          #+#    #+#              #
#    Updated: 2017/07/22 10:21:58 by akhercha         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = eval_expr

SRCS = #TODO

$(NAME): compil

compil:
	gcc -o $(NAME) $(SRCS)

clean:
	/bin/rm -f $(NAME)

re: clean all
